name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: print greeting
       run: echo "Hello World"
     - name: checking
       run: |
           echo "First Output"
           echo "Second Output"
     - name: print goodbye
       run: echo "Bye"
